/**
 * @file car_can.h
 *
 * @brief This header file was generated by cantools version 40.2.2 Sun Feb  8 18:05:04 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CAR_CAN_H
#define CAR_CAN_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CAR_CAN_HMI_INFO_FRAME_ID (0xc0b0032u)
#define CAR_CAN_INVERTER_SPEED_INFO_FRAME_ID (0xc0afefeu)
#define CAR_CAN_INVERTER_DEMANDERS_FRAME_ID (0xc09fefeu)
#define CAR_CAN_INVERTER_QD_CURRENTS_FRAME_ID (0xc08fefeu)
#define CAR_CAN_INVERTER_RMS_CURRENTS_FRAME_ID (0xc07fefeu)
#define CAR_CAN_SYSTEM_VOLTAGES_FRAME_ID (0xc06fe00u)
#define CAR_CAN_DEBUG_DEMANDS_FRAME_ID (0xc0500feu)
#define CAR_CAN_INVERTER_INFO_FRAME_ID (0xc04fe00u)
#define CAR_CAN_DRIVER_COMMANDS_FRAME_ID (0xc03fe32u)
#define CAR_CAN_INVERTER_FAULTS_FRAME_ID (0x402ff00u)
#define CAR_CAN_INVERTER_TEMP_FRAME_ID (0x401ff00u)
#define CAR_CAN_FOC_VARS_FRAME_ID (0x400ff00u)

/* Frame lengths in bytes. */
#define CAR_CAN_HMI_INFO_LENGTH (4u)
#define CAR_CAN_INVERTER_SPEED_INFO_LENGTH (4u)
#define CAR_CAN_INVERTER_DEMANDERS_LENGTH (8u)
#define CAR_CAN_INVERTER_QD_CURRENTS_LENGTH (4u)
#define CAR_CAN_INVERTER_RMS_CURRENTS_LENGTH (6u)
#define CAR_CAN_SYSTEM_VOLTAGES_LENGTH (8u)
#define CAR_CAN_DEBUG_DEMANDS_LENGTH (1u)
#define CAR_CAN_INVERTER_INFO_LENGTH (6u)
#define CAR_CAN_DRIVER_COMMANDS_LENGTH (1u)
#define CAR_CAN_INVERTER_FAULTS_LENGTH (8u)
#define CAR_CAN_INVERTER_TEMP_LENGTH (3u)
#define CAR_CAN_FOC_VARS_LENGTH (8u)

/* Extended or standard frame types. */
#define CAR_CAN_HMI_INFO_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_SPEED_INFO_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_DEMANDERS_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_QD_CURRENTS_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_RMS_CURRENTS_IS_EXTENDED (1)
#define CAR_CAN_SYSTEM_VOLTAGES_IS_EXTENDED (1)
#define CAR_CAN_DEBUG_DEMANDS_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_INFO_IS_EXTENDED (1)
#define CAR_CAN_DRIVER_COMMANDS_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_FAULTS_IS_EXTENDED (1)
#define CAR_CAN_INVERTER_TEMP_IS_EXTENDED (1)
#define CAR_CAN_FOC_VARS_IS_EXTENDED (1)

/* Frame cycle times in milliseconds. */
#define CAR_CAN_DRIVER_COMMANDS_CYCLE_TIME_MS (100u)
#define CAR_CAN_FOC_VARS_CYCLE_TIME_MS (100u)

/* Signal choices. */
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_NONE_CHOICE (0u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_TQ_PEDAL_CHOICE (1u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_SPEED_CHOICE (3u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_MTEMP_LIM_CHOICE (10u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_BEMF_LIM_CHOICE (11u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_LOWVOLT_LIM_CHOICE (12u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_TQ_CHOICE (13u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_IQ_CHOICE (14u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_TQ_RAMP_CHOICE (15u)
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_DEI_SPEED_RAMP_CHOICE (16u)

#define CAR_CAN_DEBUG_DEMANDS_INVERTER_RESET_DEMAND_NO_DEMAND_CHOICE (0u)
#define CAR_CAN_DEBUG_DEMANDS_INVERTER_RESET_DEMAND_ACTIVE_DEMAND_CHOICE (1u)

#define CAR_CAN_INVERTER_INFO_MFT_STATE_IDLE_CHOICE (0u)
#define CAR_CAN_INVERTER_INFO_MFT_STATE_RUN_CHOICE (6u)
#define CAR_CAN_INVERTER_INFO_MFT_STATE_ANY_STOP_CHOICE (7u)
#define CAR_CAN_INVERTER_INFO_MFT_STATE_STOP_CHOICE (8u)
#define CAR_CAN_INVERTER_INFO_MFT_STATE_FAULT_NOW_CHOICE (10u)
#define CAR_CAN_INVERTER_INFO_MFT_STATE_FAULT_OVER_CHOICE (11u)

#define CAR_CAN_INVERTER_INFO_DC_LINK_STATE_DC_LINK_OFF_CHOICE (0u)
#define CAR_CAN_INVERTER_INFO_DC_LINK_STATE_PRE_CHARGING_CHOICE (1u)
#define CAR_CAN_INVERTER_INFO_DC_LINK_STATE_PRE_CHARG_DONE_CHOICE (2u)
#define CAR_CAN_INVERTER_INFO_DC_LINK_STATE_DC_LINK_ON_CHOICE (3u)
#define CAR_CAN_INVERTER_INFO_DC_LINK_STATE_DC_LINK_DISCHARGING_CHOICE (4u)

#define CAR_CAN_DRIVER_COMMANDS_DEMANDED_DRIVE_DIRECTION_FORWARD_CHOICE (0u)
#define CAR_CAN_DRIVER_COMMANDS_DEMANDED_DRIVE_DIRECTION_BACKWARD_CHOICE (1u)

#define CAR_CAN_DRIVER_COMMANDS_DEMANDED_DRIVE_STATE_DISABLE_CHOICE (0u)
#define CAR_CAN_DRIVER_COMMANDS_DEMANDED_DRIVE_STATE_ENABLE_CHOICE (1u)

#define CAR_CAN_DRIVER_COMMANDS_RESET_INVERTER_ERRRORS_NO_DEMAND_CHOICE (0u)
#define CAR_CAN_DRIVER_COMMANDS_RESET_INVERTER_ERRRORS_ACTIVE_DEMAND_CHOICE (1u)

#define CAR_CAN_DRIVER_COMMANDS_DC_LINK_ACTIVE_DEMAND_NO_DEMAND_CHOICE (0u)
#define CAR_CAN_DRIVER_COMMANDS_DC_LINK_ACTIVE_DEMAND_ACTIVE_DEMAND_CHOICE (1u)

#define CAR_CAN_DRIVER_COMMANDS_PEDAL_SETTING_CANDELA_THOTTLE_AND_DIR_CHOICE (0u)
#define CAR_CAN_DRIVER_COMMANDS_PEDAL_SETTING_POT_AND_CAN_DIR_CHOICE (1u)
#define CAR_CAN_DRIVER_COMMANDS_PEDAL_SETTING_2_CHANNEL_PEDAL_AND_CAN_DIR_CHOICE (2u)
#define CAR_CAN_DRIVER_COMMANDS_PEDAL_SETTING_PEDAL_FROM_CANHMI_CHOICE (3u)

#define CAR_CAN_INVERTER_FAULTS_FLH_ACTIVE_FAULTS_NO_FAULT_CHOICE (0u)
#define CAR_CAN_INVERTER_FAULTS_FLH_ACTIVE_FAULTS_FLH_OVER_CURR_SA_CHOICE (8192u)
#define CAR_CAN_INVERTER_FAULTS_FLH_ACTIVE_FAULTS_FLH_OVER_CURR_SB_CHOICE (16384u)
#define CAR_CAN_INVERTER_FAULTS_FLH_ACTIVE_FAULTS_FLH_UNDER_VOLT_MON_CHOICE (65536u)
#define CAR_CAN_INVERTER_FAULTS_FLH_ACTIVE_FAULTS_FLH_OVER_VOLT_DCM_CHOICE (65538u)

#define CAR_CAN_INVERTER_FAULTS_FLH_PASSIVE_FAULTS_NO_FAULT_CHOICE (0u)
#define CAR_CAN_INVERTER_FAULTS_FLH_PASSIVE_FAULTS_FLH_OVER_CURR_SA_CHOICE (8192u)
#define CAR_CAN_INVERTER_FAULTS_FLH_PASSIVE_FAULTS_FLH_OVER_CURR_SB_CHOICE (16384u)
#define CAR_CAN_INVERTER_FAULTS_FLH_PASSIVE_FAULTS_FLH_UNDER_VOLT_MON_CHOICE (65536u)
#define CAR_CAN_INVERTER_FAULTS_FLH_PASSIVE_FAULTS_FLH_OVER_VOLT_DCM_CHOICE (65538u)

/* Frame Names. */
#define CAR_CAN_HMI_INFO_NAME "HmiInfo"
#define CAR_CAN_INVERTER_SPEED_INFO_NAME "InverterSpeedInfo"
#define CAR_CAN_INVERTER_DEMANDERS_NAME "InverterDemanders"
#define CAR_CAN_INVERTER_QD_CURRENTS_NAME "InverterQDCurrents"
#define CAR_CAN_INVERTER_RMS_CURRENTS_NAME "InverterRMSCurrents"
#define CAR_CAN_SYSTEM_VOLTAGES_NAME "SystemVoltages"
#define CAR_CAN_DEBUG_DEMANDS_NAME "DebugDemands"
#define CAR_CAN_INVERTER_INFO_NAME "InverterInfo"
#define CAR_CAN_DRIVER_COMMANDS_NAME "DriverCommands"
#define CAR_CAN_INVERTER_FAULTS_NAME "InverterFaults"
#define CAR_CAN_INVERTER_TEMP_NAME "InverterTemp"
#define CAR_CAN_FOC_VARS_NAME "FOCVars"

/* Signal Names. */
#define CAR_CAN_HMI_INFO_HMI1MS_TICKS_NAME "Hmi1msTicks"
#define CAR_CAN_INVERTER_SPEED_INFO_EM_SPEED01_HZ_NAME "EmSpeed01Hz"
#define CAR_CAN_INVERTER_SPEED_INFO_EM_SPEED_RPM_NAME "EmSpeedRpm"
#define CAR_CAN_INVERTER_DEMANDERS_ACTIVE_DEMANDER_NAME "ActiveDemander"
#define CAR_CAN_INVERTER_DEMANDERS_IQ_DEMAND_NAME "IQ_Demand"
#define CAR_CAN_INVERTER_DEMANDERS_ID_DEMAND_NAME "ID_Demand"
#define CAR_CAN_INVERTER_DEMANDERS_PEDAL_REQUEST_NAME "PedalRequest"
#define CAR_CAN_INVERTER_QD_CURRENTS_CURRENT_ID_NAME "Current_Id"
#define CAR_CAN_INVERTER_QD_CURRENTS_CURRENT_IQ_NAME "Current_Iq"
#define CAR_CAN_INVERTER_RMS_CURRENTS_PHASE_URMS_CURRENT_NAME "PhaseURMSCurrent"
#define CAR_CAN_INVERTER_RMS_CURRENTS_PHASE_VRMS_CURRENT_NAME "PhaseVRMSCurrent"
#define CAR_CAN_INVERTER_RMS_CURRENTS_PHASE_WRMS_CURRENT_NAME "PhaseWRMSCurrent"
#define CAR_CAN_SYSTEM_VOLTAGES_MEAS12_V_NAME "Meas12V"
#define CAR_CAN_SYSTEM_VOLTAGES_MEAS5_V_NAME "Meas5V"
#define CAR_CAN_SYSTEM_VOLTAGES_MEAS_DC_LINK_NAME "MeasDCLink"
#define CAR_CAN_SYSTEM_VOLTAGES_MEAS_BATT_VOLTAGE_NAME "MeasBattVoltage"
#define CAR_CAN_DEBUG_DEMANDS_INVERTER_RESET_DEMAND_NAME "InverterResetDemand"
#define CAR_CAN_INVERTER_INFO_INVERTER1MS_TICKS_NAME "Inverter1msTicks"
#define CAR_CAN_INVERTER_INFO_MFT_STATE_NAME "MftState"
#define CAR_CAN_INVERTER_INFO_DC_LINK_STATE_NAME "DCLinkState"
#define CAR_CAN_DRIVER_COMMANDS_DEMANDED_DRIVE_DIRECTION_NAME "DemandedDriveDirection"
#define CAR_CAN_DRIVER_COMMANDS_DEMANDED_DRIVE_STATE_NAME "DemandedDriveState"
#define CAR_CAN_DRIVER_COMMANDS_RESET_INVERTER_ERRRORS_NAME "ResetInverterErrrors"
#define CAR_CAN_DRIVER_COMMANDS_DC_LINK_ACTIVE_DEMAND_NAME "DCLinkActiveDemand"
#define CAR_CAN_DRIVER_COMMANDS_PEDAL_SETTING_NAME "PedalSetting"
#define CAR_CAN_INVERTER_FAULTS_FLH_ACTIVE_FAULTS_NAME "FLH_activeFaults"
#define CAR_CAN_INVERTER_FAULTS_FLH_PASSIVE_FAULTS_NAME "FLH_passiveFaults"
#define CAR_CAN_INVERTER_TEMP_INVERTER_TEMP_U_NAME "InverterTempU"
#define CAR_CAN_INVERTER_TEMP_INVERTER_TEMP_V_NAME "InverterTempV"
#define CAR_CAN_INVERTER_TEMP_INVERTER_TEMP_W_NAME "InverterTempW"
#define CAR_CAN_FOC_VARS_FOC_CURRENT_ID_NAME "FOCCurrent_Id"
#define CAR_CAN_FOC_VARS_FOC_CURRENT_IQ_NAME "FOCCurrent_Iq"
#define CAR_CAN_FOC_VARS_ID_REF_NAME "Id_ref"
#define CAR_CAN_FOC_VARS_IQ_REF_NAME "Iq_ref"

/**
 * Signals in message HmiInfo.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_hmi_info_t {
    /**
     * Range: 0..4294967295 (0..4294967295 ms)
     * Scale: 1
     * Offset: 0
     */
    uint32_t hmi1ms_ticks;
};

/**
 * Signals in message InverterSpeedInfo.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_speed_info_t {
    /**
     * Range: -32768..32767 (-32768..32767 01Hz)
     * Scale: 1
     * Offset: 0
     */
    int16_t em_speed01_hz;

    /**
     * Range: -8192..8191 (-8192..8191 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t em_speed_rpm;
};

/**
 * Signals in message InverterDemanders.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_demanders_t {
    /**
     * Range: 0..63 (0..63 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t active_demander;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t iq_demand;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t id_demand;

    /**
     * Range: 0..1023 (0..102.3 %)
     * Scale: 0.1
     * Offset: 0
     */
    uint16_t pedal_request;
};

/**
 * Signals in message InverterQDCurrents.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_qd_currents_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t current_id;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t current_iq;
};

/**
 * Signals in message InverterRMSCurrents.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_rms_currents_t {
    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t phase_urms_current;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t phase_vrms_current;

    /**
     * Range: -32768..32767 (-3276.8..3276.7 A)
     * Scale: 0.1
     * Offset: 0
     */
    int16_t phase_wrms_current;
};

/**
 * Signals in message SystemVoltages.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_system_voltages_t {
    /**
     * Range: 0..65535 (0..65.535 V)
     * Scale: 0.001
     * Offset: 0
     */
    uint16_t meas12_v;

    /**
     * Range: 0..255 (0..25.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t meas5_v;

    /**
     * Range: 0..65535 (0..655.35 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t meas_dc_link;

    /**
     * Range: 0..65535 (0..655.35 V)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t meas_batt_voltage;
};

/**
 * Signals in message DebugDemands.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_debug_demands_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t inverter_reset_demand;
};

/**
 * Signals in message InverterInfo.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_info_t {
    /**
     * Range: 0..4294967295 (0..4294967295 ms)
     * Scale: 1
     * Offset: 0
     */
    uint32_t inverter1ms_ticks;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t mft_state;

    /**
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t dc_link_state;
};

/**
 * Signals in message DriverCommands.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_driver_commands_t {
    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t demanded_drive_direction;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t demanded_drive_state;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t reset_inverter_errrors;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t dc_link_active_demand;

    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pedal_setting;
};

/**
 * Signals in message InverterFaults.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_faults_t {
    /**
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t flh_active_faults;

    /**
     * Range: 0..4294967295 (0..4294967295 -)
     * Scale: 1
     * Offset: 0
     */
    uint32_t flh_passive_faults;
};

/**
 * Signals in message InverterTemp.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_inverter_temp_t {
    /**
     * Range: 0..255 (0..127.5 degree C)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t inverter_temp_u;

    /**
     * Range: 0..255 (0..127.5 degree C)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t inverter_temp_v;

    /**
     * Range: 0..255 (0..127.5 degree C)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t inverter_temp_w;
};

/**
 * Signals in message FOCVars.
 *
 * All signal values are as on the CAN bus.
 */
struct car_can_foc_vars_t {
    /**
     * Range: -32768..32767 (-32768..32767 A)
     * Scale: 1
     * Offset: 0
     */
    int16_t foc_current_id;

    /**
     * Range: -32768..32767 (-32768..32767 A)
     * Scale: 1
     * Offset: 0
     */
    int16_t foc_current_iq;

    /**
     * Range: -32768..32767 (-32768..32767 q1.15)
     * Scale: 1
     * Offset: 0
     */
    int16_t id_ref;

    /**
     * Range: -32768..32767 (-32768..32767 -)
     * Scale: 1
     * Offset: 0
     */
    int16_t iq_ref;
};

/**
 * Pack message HmiInfo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_hmi_info_pack(
    uint8_t *dst_p,
    const struct car_can_hmi_info_t *src_p,
    size_t size);

/**
 * Unpack message HmiInfo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_hmi_info_unpack(
    struct car_can_hmi_info_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from HmiInfo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_hmi_info_init(struct car_can_hmi_info_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t car_can_hmi_info_hmi1ms_ticks_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_hmi_info_hmi1ms_ticks_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_hmi_info_hmi1ms_ticks_is_in_range(uint32_t value);

/**
 * Pack message InverterSpeedInfo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_speed_info_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_speed_info_t *src_p,
    size_t size);

/**
 * Unpack message InverterSpeedInfo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_speed_info_unpack(
    struct car_can_inverter_speed_info_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterSpeedInfo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_speed_info_init(struct car_can_inverter_speed_info_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_speed_info_em_speed01_hz_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_speed_info_em_speed01_hz_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_speed_info_em_speed01_hz_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_speed_info_em_speed_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_speed_info_em_speed_rpm_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_speed_info_em_speed_rpm_is_in_range(int16_t value);

/**
 * Pack message InverterDemanders.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_demanders_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_demanders_t *src_p,
    size_t size);

/**
 * Unpack message InverterDemanders.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_demanders_unpack(
    struct car_can_inverter_demanders_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterDemanders.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_demanders_init(struct car_can_inverter_demanders_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_inverter_demanders_active_demander_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_demanders_active_demander_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_demanders_active_demander_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_demanders_iq_demand_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_demanders_iq_demand_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_demanders_iq_demand_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_demanders_id_demand_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_demanders_id_demand_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_demanders_id_demand_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t car_can_inverter_demanders_pedal_request_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_demanders_pedal_request_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_demanders_pedal_request_is_in_range(uint16_t value);

/**
 * Pack message InverterQDCurrents.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_qd_currents_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_qd_currents_t *src_p,
    size_t size);

/**
 * Unpack message InverterQDCurrents.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_qd_currents_unpack(
    struct car_can_inverter_qd_currents_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterQDCurrents.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_qd_currents_init(struct car_can_inverter_qd_currents_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_qd_currents_current_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_qd_currents_current_id_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_qd_currents_current_id_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_qd_currents_current_iq_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_qd_currents_current_iq_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_qd_currents_current_iq_is_in_range(int16_t value);

/**
 * Pack message InverterRMSCurrents.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_rms_currents_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_rms_currents_t *src_p,
    size_t size);

/**
 * Unpack message InverterRMSCurrents.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_rms_currents_unpack(
    struct car_can_inverter_rms_currents_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterRMSCurrents.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_rms_currents_init(struct car_can_inverter_rms_currents_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_rms_currents_phase_urms_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_rms_currents_phase_urms_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_rms_currents_phase_urms_current_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_rms_currents_phase_vrms_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_rms_currents_phase_vrms_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_rms_currents_phase_vrms_current_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_inverter_rms_currents_phase_wrms_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_rms_currents_phase_wrms_current_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_rms_currents_phase_wrms_current_is_in_range(int16_t value);

/**
 * Pack message SystemVoltages.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_system_voltages_pack(
    uint8_t *dst_p,
    const struct car_can_system_voltages_t *src_p,
    size_t size);

/**
 * Unpack message SystemVoltages.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_system_voltages_unpack(
    struct car_can_system_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from SystemVoltages.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_system_voltages_init(struct car_can_system_voltages_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t car_can_system_voltages_meas12_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_system_voltages_meas12_v_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_system_voltages_meas12_v_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_system_voltages_meas5_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_system_voltages_meas5_v_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_system_voltages_meas5_v_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t car_can_system_voltages_meas_dc_link_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_system_voltages_meas_dc_link_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_system_voltages_meas_dc_link_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t car_can_system_voltages_meas_batt_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_system_voltages_meas_batt_voltage_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_system_voltages_meas_batt_voltage_is_in_range(uint16_t value);

/**
 * Pack message DebugDemands.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_debug_demands_pack(
    uint8_t *dst_p,
    const struct car_can_debug_demands_t *src_p,
    size_t size);

/**
 * Unpack message DebugDemands.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_debug_demands_unpack(
    struct car_can_debug_demands_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from DebugDemands.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_debug_demands_init(struct car_can_debug_demands_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_debug_demands_inverter_reset_demand_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_debug_demands_inverter_reset_demand_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_debug_demands_inverter_reset_demand_is_in_range(uint8_t value);

/**
 * Pack message InverterInfo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_info_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_info_t *src_p,
    size_t size);

/**
 * Unpack message InverterInfo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_info_unpack(
    struct car_can_inverter_info_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterInfo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_info_init(struct car_can_inverter_info_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t car_can_inverter_info_inverter1ms_ticks_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_info_inverter1ms_ticks_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_info_inverter1ms_ticks_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_inverter_info_mft_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_info_mft_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_info_mft_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_inverter_info_dc_link_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_info_dc_link_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_info_dc_link_state_is_in_range(uint8_t value);

/**
 * Pack message DriverCommands.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_driver_commands_pack(
    uint8_t *dst_p,
    const struct car_can_driver_commands_t *src_p,
    size_t size);

/**
 * Unpack message DriverCommands.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_driver_commands_unpack(
    struct car_can_driver_commands_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from DriverCommands.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_driver_commands_init(struct car_can_driver_commands_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_driver_commands_demanded_drive_direction_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_driver_commands_demanded_drive_direction_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_driver_commands_demanded_drive_direction_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_driver_commands_demanded_drive_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_driver_commands_demanded_drive_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_driver_commands_demanded_drive_state_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_driver_commands_reset_inverter_errrors_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_driver_commands_reset_inverter_errrors_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_driver_commands_reset_inverter_errrors_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_driver_commands_dc_link_active_demand_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_driver_commands_dc_link_active_demand_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_driver_commands_dc_link_active_demand_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_driver_commands_pedal_setting_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_driver_commands_pedal_setting_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_driver_commands_pedal_setting_is_in_range(uint8_t value);

/**
 * Pack message InverterFaults.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_faults_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_faults_t *src_p,
    size_t size);

/**
 * Unpack message InverterFaults.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_faults_unpack(
    struct car_can_inverter_faults_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterFaults.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_faults_init(struct car_can_inverter_faults_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t car_can_inverter_faults_flh_active_faults_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_faults_flh_active_faults_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_faults_flh_active_faults_is_in_range(uint32_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint32_t car_can_inverter_faults_flh_passive_faults_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_faults_flh_passive_faults_decode(uint32_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_faults_flh_passive_faults_is_in_range(uint32_t value);

/**
 * Pack message InverterTemp.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_inverter_temp_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_temp_t *src_p,
    size_t size);

/**
 * Unpack message InverterTemp.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_inverter_temp_unpack(
    struct car_can_inverter_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from InverterTemp.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_inverter_temp_init(struct car_can_inverter_temp_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_inverter_temp_inverter_temp_u_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_temp_inverter_temp_u_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_temp_inverter_temp_u_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_inverter_temp_inverter_temp_v_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_temp_inverter_temp_v_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_temp_inverter_temp_v_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t car_can_inverter_temp_inverter_temp_w_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_inverter_temp_inverter_temp_w_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_inverter_temp_inverter_temp_w_is_in_range(uint8_t value);

/**
 * Pack message FOCVars.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int car_can_foc_vars_pack(
    uint8_t *dst_p,
    const struct car_can_foc_vars_t *src_p,
    size_t size);

/**
 * Unpack message FOCVars.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int car_can_foc_vars_unpack(
    struct car_can_foc_vars_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from FOCVars.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int car_can_foc_vars_init(struct car_can_foc_vars_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_foc_vars_foc_current_id_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_foc_vars_foc_current_id_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_foc_vars_foc_current_id_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_foc_vars_foc_current_iq_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_foc_vars_foc_current_iq_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_foc_vars_foc_current_iq_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_foc_vars_id_ref_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_foc_vars_id_ref_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_foc_vars_id_ref_is_in_range(int16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t car_can_foc_vars_iq_ref_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double car_can_foc_vars_iq_ref_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool car_can_foc_vars_iq_ref_is_in_range(int16_t value);


#ifdef __cplusplus
}
#endif

#endif
