/**
 * @file car_can.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Sat Jun  7 14:32:28 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "car_can.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int car_can_inverter_demanders_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_demanders_t *src_p,
    size_t size)
{
    uint16_t id_demand;
    uint16_t iq_demand;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->active_demander, 0u, 0x3fu);
    iq_demand = (uint16_t)src_p->iq_demand;
    dst_p[2] |= pack_left_shift_u16(iq_demand, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(iq_demand, 8u, 0xffu);
    id_demand = (uint16_t)src_p->id_demand;
    dst_p[4] |= pack_left_shift_u16(id_demand, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(id_demand, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->pedal_request, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->pedal_request, 8u, 0x03u);

    return (8);
}

int car_can_inverter_demanders_unpack(
    struct car_can_inverter_demanders_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t id_demand;
    uint16_t iq_demand;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->active_demander = unpack_right_shift_u8(src_p[0], 0u, 0x3fu);
    iq_demand = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    iq_demand |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->iq_demand = (int16_t)iq_demand;
    id_demand = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    id_demand |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->id_demand = (int16_t)id_demand;
    dst_p->pedal_request = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->pedal_request |= unpack_left_shift_u16(src_p[7], 8u, 0x03u);

    return (0);
}

int car_can_inverter_demanders_init(struct car_can_inverter_demanders_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_inverter_demanders_t));

    return 0;
}

uint8_t car_can_inverter_demanders_active_demander_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_inverter_demanders_active_demander_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_inverter_demanders_active_demander_is_in_range(uint8_t value)
{
    return (value <= 63u);
}

int16_t car_can_inverter_demanders_iq_demand_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_demanders_iq_demand_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_demanders_iq_demand_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_inverter_demanders_id_demand_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_demanders_id_demand_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_demanders_id_demand_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint16_t car_can_inverter_demanders_pedal_request_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double car_can_inverter_demanders_pedal_request_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_demanders_pedal_request_is_in_range(uint16_t value)
{
    return (value <= 1023u);
}

int car_can_inverter_qd_currents_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_qd_currents_t *src_p,
    size_t size)
{
    uint16_t current_id;
    uint16_t current_iq;

    if (size < 4u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 4);

    current_id = (uint16_t)src_p->current_id;
    dst_p[0] |= pack_left_shift_u16(current_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(current_id, 8u, 0xffu);
    current_iq = (uint16_t)src_p->current_iq;
    dst_p[2] |= pack_left_shift_u16(current_iq, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(current_iq, 8u, 0xffu);

    return (4);
}

int car_can_inverter_qd_currents_unpack(
    struct car_can_inverter_qd_currents_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t current_id;
    uint16_t current_iq;

    if (size < 4u) {
        return (-EINVAL);
    }

    current_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    current_id |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->current_id = (int16_t)current_id;
    current_iq = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    current_iq |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_iq = (int16_t)current_iq;

    return (0);
}

int car_can_inverter_qd_currents_init(struct car_can_inverter_qd_currents_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_inverter_qd_currents_t));

    return 0;
}

int16_t car_can_inverter_qd_currents_current_id_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_qd_currents_current_id_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_qd_currents_current_id_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_inverter_qd_currents_current_iq_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_qd_currents_current_iq_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_qd_currents_current_iq_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int car_can_inverter_rms_currents_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_rms_currents_t *src_p,
    size_t size)
{
    uint16_t phase_urms_current;
    uint16_t phase_vrms_current;
    uint16_t phase_wrms_current;

    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    phase_urms_current = (uint16_t)src_p->phase_urms_current;
    dst_p[0] |= pack_left_shift_u16(phase_urms_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(phase_urms_current, 8u, 0xffu);
    phase_vrms_current = (uint16_t)src_p->phase_vrms_current;
    dst_p[2] |= pack_left_shift_u16(phase_vrms_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(phase_vrms_current, 8u, 0xffu);
    phase_wrms_current = (uint16_t)src_p->phase_wrms_current;
    dst_p[4] |= pack_left_shift_u16(phase_wrms_current, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(phase_wrms_current, 8u, 0xffu);

    return (6);
}

int car_can_inverter_rms_currents_unpack(
    struct car_can_inverter_rms_currents_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t phase_urms_current;
    uint16_t phase_vrms_current;
    uint16_t phase_wrms_current;

    if (size < 6u) {
        return (-EINVAL);
    }

    phase_urms_current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    phase_urms_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->phase_urms_current = (int16_t)phase_urms_current;
    phase_vrms_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    phase_vrms_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->phase_vrms_current = (int16_t)phase_vrms_current;
    phase_wrms_current = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    phase_wrms_current |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->phase_wrms_current = (int16_t)phase_wrms_current;

    return (0);
}

int car_can_inverter_rms_currents_init(struct car_can_inverter_rms_currents_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_inverter_rms_currents_t));

    return 0;
}

int16_t car_can_inverter_rms_currents_phase_urms_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_rms_currents_phase_urms_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_rms_currents_phase_urms_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_inverter_rms_currents_phase_vrms_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_rms_currents_phase_vrms_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_rms_currents_phase_vrms_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_inverter_rms_currents_phase_wrms_current_encode(double value)
{
    return (int16_t)(value / 0.1);
}

double car_can_inverter_rms_currents_phase_wrms_current_decode(int16_t value)
{
    return ((double)value * 0.1);
}

bool car_can_inverter_rms_currents_phase_wrms_current_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int car_can_system_voltages_pack(
    uint8_t *dst_p,
    const struct car_can_system_voltages_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->meas12_v, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->meas12_v, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->meas5_v, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->meas_dc_link, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->meas_dc_link, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->meas_batt_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->meas_batt_voltage, 8u, 0xffu);

    return (8);
}

int car_can_system_voltages_unpack(
    struct car_can_system_voltages_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->meas12_v = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->meas12_v |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->meas5_v = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->meas_dc_link = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->meas_dc_link |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->meas_batt_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->meas_batt_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int car_can_system_voltages_init(struct car_can_system_voltages_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_system_voltages_t));

    return 0;
}

uint16_t car_can_system_voltages_meas12_v_encode(double value)
{
    return (uint16_t)(value / 0.001);
}

double car_can_system_voltages_meas12_v_decode(uint16_t value)
{
    return ((double)value * 0.001);
}

bool car_can_system_voltages_meas12_v_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t car_can_system_voltages_meas5_v_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double car_can_system_voltages_meas5_v_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool car_can_system_voltages_meas5_v_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t car_can_system_voltages_meas_dc_link_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double car_can_system_voltages_meas_dc_link_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool car_can_system_voltages_meas_dc_link_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t car_can_system_voltages_meas_batt_voltage_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double car_can_system_voltages_meas_batt_voltage_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool car_can_system_voltages_meas_batt_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int car_can_debug_demands_pack(
    uint8_t *dst_p,
    const struct car_can_debug_demands_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->inverter_reset_demand, 0u, 0x01u);

    return (1);
}

int car_can_debug_demands_unpack(
    struct car_can_debug_demands_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->inverter_reset_demand = unpack_right_shift_u8(src_p[0], 0u, 0x01u);

    return (0);
}

int car_can_debug_demands_init(struct car_can_debug_demands_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_debug_demands_t));

    return 0;
}

uint8_t car_can_debug_demands_inverter_reset_demand_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_debug_demands_inverter_reset_demand_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_debug_demands_inverter_reset_demand_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int car_can_inverter_info_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_info_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 6);

    dst_p[0] |= pack_left_shift_u32(src_p->inverter1ms_ticks, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->inverter1ms_ticks, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->inverter1ms_ticks, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->inverter1ms_ticks, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->mft_state, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->dc_link_state, 0u, 0x07u);

    return (6);
}

int car_can_inverter_info_unpack(
    struct car_can_inverter_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 6u) {
        return (-EINVAL);
    }

    dst_p->inverter1ms_ticks = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->inverter1ms_ticks |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->inverter1ms_ticks |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->inverter1ms_ticks |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->mft_state = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->dc_link_state = unpack_right_shift_u8(src_p[5], 0u, 0x07u);

    return (0);
}

int car_can_inverter_info_init(struct car_can_inverter_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_inverter_info_t));

    return 0;
}

uint32_t car_can_inverter_info_inverter1ms_ticks_encode(double value)
{
    return (uint32_t)(value);
}

double car_can_inverter_info_inverter1ms_ticks_decode(uint32_t value)
{
    return ((double)value);
}

bool car_can_inverter_info_inverter1ms_ticks_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint8_t car_can_inverter_info_mft_state_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_inverter_info_mft_state_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_inverter_info_mft_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t car_can_inverter_info_dc_link_state_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_inverter_info_dc_link_state_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_inverter_info_dc_link_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

int car_can_driver_commands_pack(
    uint8_t *dst_p,
    const struct car_can_driver_commands_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->demanded_drive_direction, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->demanded_drive_state, 1u, 0x02u);
    dst_p[0] |= pack_left_shift_u8(src_p->reset_inverter_errrors, 2u, 0x04u);
    dst_p[0] |= pack_left_shift_u8(src_p->dc_link_active_demand, 3u, 0x08u);

    return (1);
}

int car_can_driver_commands_unpack(
    struct car_can_driver_commands_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->demanded_drive_direction = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->demanded_drive_state = unpack_right_shift_u8(src_p[0], 1u, 0x02u);
    dst_p->reset_inverter_errrors = unpack_right_shift_u8(src_p[0], 2u, 0x04u);
    dst_p->dc_link_active_demand = unpack_right_shift_u8(src_p[0], 3u, 0x08u);

    return (0);
}

int car_can_driver_commands_init(struct car_can_driver_commands_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_driver_commands_t));

    return 0;
}

uint8_t car_can_driver_commands_demanded_drive_direction_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_driver_commands_demanded_drive_direction_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_driver_commands_demanded_drive_direction_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t car_can_driver_commands_demanded_drive_state_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_driver_commands_demanded_drive_state_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_driver_commands_demanded_drive_state_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t car_can_driver_commands_reset_inverter_errrors_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_driver_commands_reset_inverter_errrors_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_driver_commands_reset_inverter_errrors_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t car_can_driver_commands_dc_link_active_demand_encode(double value)
{
    return (uint8_t)(value);
}

double car_can_driver_commands_dc_link_active_demand_decode(uint8_t value)
{
    return ((double)value);
}

bool car_can_driver_commands_dc_link_active_demand_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int car_can_inverter_faults_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_faults_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->flh_active_faults, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->flh_active_faults, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->flh_active_faults, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->flh_active_faults, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->flh_passive_faults, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->flh_passive_faults, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->flh_passive_faults, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->flh_passive_faults, 24u, 0xffu);

    return (8);
}

int car_can_inverter_faults_unpack(
    struct car_can_inverter_faults_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->flh_active_faults = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->flh_active_faults |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->flh_active_faults |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->flh_active_faults |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->flh_passive_faults = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->flh_passive_faults |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->flh_passive_faults |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->flh_passive_faults |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int car_can_inverter_faults_init(struct car_can_inverter_faults_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_inverter_faults_t));

    return 0;
}

uint32_t car_can_inverter_faults_flh_active_faults_encode(double value)
{
    return (uint32_t)(value);
}

double car_can_inverter_faults_flh_active_faults_decode(uint32_t value)
{
    return ((double)value);
}

bool car_can_inverter_faults_flh_active_faults_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t car_can_inverter_faults_flh_passive_faults_encode(double value)
{
    return (uint32_t)(value);
}

double car_can_inverter_faults_flh_passive_faults_decode(uint32_t value)
{
    return ((double)value);
}

bool car_can_inverter_faults_flh_passive_faults_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int car_can_inverter_temp_pack(
    uint8_t *dst_p,
    const struct car_can_inverter_temp_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 3);

    dst_p[0] |= pack_left_shift_u8(src_p->inverter_temp_u, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->inverter_temp_v, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->inverter_temp_w, 0u, 0xffu);

    return (3);
}

int car_can_inverter_temp_unpack(
    struct car_can_inverter_temp_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 3u) {
        return (-EINVAL);
    }

    dst_p->inverter_temp_u = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->inverter_temp_v = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->inverter_temp_w = unpack_right_shift_u8(src_p[2], 0u, 0xffu);

    return (0);
}

int car_can_inverter_temp_init(struct car_can_inverter_temp_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_inverter_temp_t));

    return 0;
}

uint8_t car_can_inverter_temp_inverter_temp_u_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double car_can_inverter_temp_inverter_temp_u_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool car_can_inverter_temp_inverter_temp_u_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t car_can_inverter_temp_inverter_temp_v_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double car_can_inverter_temp_inverter_temp_v_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool car_can_inverter_temp_inverter_temp_v_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t car_can_inverter_temp_inverter_temp_w_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double car_can_inverter_temp_inverter_temp_w_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool car_can_inverter_temp_inverter_temp_w_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int car_can_foc_vars_pack(
    uint8_t *dst_p,
    const struct car_can_foc_vars_t *src_p,
    size_t size)
{
    uint16_t foc_current_id;
    uint16_t foc_current_iq;
    uint16_t id_ref;
    uint16_t iq_ref;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    foc_current_id = (uint16_t)src_p->foc_current_id;
    dst_p[0] |= pack_left_shift_u16(foc_current_id, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(foc_current_id, 8u, 0xffu);
    foc_current_iq = (uint16_t)src_p->foc_current_iq;
    dst_p[2] |= pack_left_shift_u16(foc_current_iq, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(foc_current_iq, 8u, 0xffu);
    id_ref = (uint16_t)src_p->id_ref;
    dst_p[4] |= pack_left_shift_u16(id_ref, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(id_ref, 8u, 0xffu);
    iq_ref = (uint16_t)src_p->iq_ref;
    dst_p[6] |= pack_left_shift_u16(iq_ref, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(iq_ref, 8u, 0xffu);

    return (8);
}

int car_can_foc_vars_unpack(
    struct car_can_foc_vars_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t foc_current_id;
    uint16_t foc_current_iq;
    uint16_t id_ref;
    uint16_t iq_ref;

    if (size < 8u) {
        return (-EINVAL);
    }

    foc_current_id = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    foc_current_id |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->foc_current_id = (int16_t)foc_current_id;
    foc_current_iq = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    foc_current_iq |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->foc_current_iq = (int16_t)foc_current_iq;
    id_ref = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    id_ref |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->id_ref = (int16_t)id_ref;
    iq_ref = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    iq_ref |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);
    dst_p->iq_ref = (int16_t)iq_ref;

    return (0);
}

int car_can_foc_vars_init(struct car_can_foc_vars_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct car_can_foc_vars_t));

    return 0;
}

int16_t car_can_foc_vars_foc_current_id_encode(double value)
{
    return (int16_t)(value);
}

double car_can_foc_vars_foc_current_id_decode(int16_t value)
{
    return ((double)value);
}

bool car_can_foc_vars_foc_current_id_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_foc_vars_foc_current_iq_encode(double value)
{
    return (int16_t)(value);
}

double car_can_foc_vars_foc_current_iq_decode(int16_t value)
{
    return ((double)value);
}

bool car_can_foc_vars_foc_current_iq_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_foc_vars_id_ref_encode(double value)
{
    return (int16_t)(value);
}

double car_can_foc_vars_id_ref_decode(int16_t value)
{
    return ((double)value);
}

bool car_can_foc_vars_id_ref_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

int16_t car_can_foc_vars_iq_ref_encode(double value)
{
    return (int16_t)(value);
}

double car_can_foc_vars_iq_ref_decode(int16_t value)
{
    return ((double)value);
}

bool car_can_foc_vars_iq_ref_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}
