/****************************************************************************
 * apps/hmi_manager/uiux/screen/screen_manager.c
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * Design: Two-phase initialization
 *
 * Phase 1 - screen_manager_init() - called from main() before
 *   threads:
 *   Creates bare lv_obj_t screens (no image objects, no widgets).
 *   Loads SCREEN_SPLASH as active screen (black until phase 2).
 *   Safe because lv_obj_create(NULL) does not trigger rendering.
 *
 * Phase 2 - screen_manager_setup_assets() - called from
 *   lvgl_thread:
 *   Attaches lv_img to splash screen.
 *   Attaches lv_img to dashboard screen (theme bg + widgets).
 *   Attaches lv_img to theme screen (theme bg only, no widgets).
 *   Calls widgets_init() on dashboard screen in correct LVGL
 *   context.
 *   This is the ONLY correct place to create LVGL objects with
 *   assets.
 *
 * Asset selection is driven by Kconfig:
 *   CONFIG_HMI_SPLASH_xxx -> splash screen image
 *   CONFIG_HMI_THEME_xxx  -> dashboard + theme screen image
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include <stdio.h>
#include <errno.h>
#include <lvgl/lvgl.h>

#include "screen_manager.h"
#include "../widgets.h"

/****************************************************************************
 * Splash Screen Asset Declaration
 *
 * Only one splash asset is compiled at a time (Kconfig choice).
 * The extern symbol must match the variable name inside the
 * asset .c file generated by png2code.py.
 ****************************************************************************/

#if defined(CONFIG_HMI_SPLASH_BIFROSTOX_FLAT)
extern const lv_img_dsc_t img_bifrostox_flat;
#  define SPLASH_ASSET  (&img_bifrostox_flat)
#elif defined(CONFIG_HMI_SPLASH_BIFROSTOX_NORDIC)
extern const lv_img_dsc_t img_bifrostox_nordic;
#  define SPLASH_ASSET  (&img_bifrostox_nordic)
#elif defined(CONFIG_HMI_SPLASH_MAIN_CYBERPUNK)
extern const lv_img_dsc_t img_main_cyberpunk;
#  define SPLASH_ASSET  (&img_main_cyberpunk)
#elif defined(CONFIG_HMI_SPLASH_MAIN_MODERN)
extern const lv_img_dsc_t img_main_modern;
#  define SPLASH_ASSET  (&img_main_modern)
#elif defined(CONFIG_HMI_SPLASH_MAIN_RETRO)
extern const lv_img_dsc_t img_main_retro;
#  define SPLASH_ASSET  (&img_main_retro)
#else
#  define SPLASH_ASSET  NULL
#endif

/****************************************************************************
 * Dashboard Theme Asset Declaration
 *
 * Background image for SCREEN_DASHBOARD (with widgets) and
 * SCREEN_THEME (image only, no widgets). Both screens share
 * the same asset but SCREEN_THEME has no LVGL widget overlay.
 * Only one theme asset is compiled at a time (Kconfig choice).
 ****************************************************************************/

#if defined(CONFIG_HMI_THEME_BIFROSTOX_FLAT)
extern const lv_img_dsc_t img_bifrostox_flat;
#  define THEME_ASSET  (&img_bifrostox_flat)
#elif defined(CONFIG_HMI_THEME_BIFROSTOX_NORDIC)
extern const lv_img_dsc_t img_bifrostox_nordic;
#  define THEME_ASSET  (&img_bifrostox_nordic)
#elif defined(CONFIG_HMI_THEME_MAIN_CYBERPUNK)
extern const lv_img_dsc_t img_main_cyberpunk;
#  define THEME_ASSET  (&img_main_cyberpunk)
#elif defined(CONFIG_HMI_THEME_MAIN_MODERN)
extern const lv_img_dsc_t img_main_modern;
#  define THEME_ASSET  (&img_main_modern)
#elif defined(CONFIG_HMI_THEME_MAIN_RETRO)
extern const lv_img_dsc_t img_main_retro;
#  define THEME_ASSET  (&img_main_retro)
#elif defined(CONFIG_HMI_THEME_MAIN_RETRO_T3)
extern const lv_img_dsc_t img_main_retro_t3;
#  define THEME_ASSET  (&img_main_retro_t3)
#else
#  define THEME_ASSET  NULL
#endif

/****************************************************************************
 * Private Data
 ****************************************************************************/

/* One lv_obj_t* per screen - created once in phase 1, kept
 * alive. LVGL screens are lightweight; only the active one
 * is rendered.
 */

static lv_obj_t *g_screens[SCREEN_COUNT];
static screen_id_t g_current = SCREEN_COUNT; /* invalid sentinel */
static bool g_assets_ready   = false;

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: build_screen_skeleton
 *
 * Description:
 *   Create a bare black screen with no child objects.
 *   Safe to call before lvgl_thread starts.
 *
 * Returned Value:
 *   Pointer to lv_obj_t, or NULL on failure.
 ****************************************************************************/

static lv_obj_t *build_screen_skeleton(void)
{
  lv_obj_t *scr;

  scr = lv_obj_create(NULL);
  if (scr == NULL)
    {
      return NULL;
    }

  lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), 0);
  lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

  return scr;
}

/****************************************************************************
 * Name: attach_fullscreen_image
 *
 * Description:
 *   Create an lv_img child on the given screen and set its
 *   source to the provided image descriptor. Position at (0,0)
 *   for full-screen coverage (480x320).
 *
 * Input Parameters:
 *   parent - Screen object to attach the image to
 *   src    - Pointer to lv_img_dsc_t asset (NULL = skip)
 *
 * Returned Value:
 *   0 on success, -ENOMEM if lv_img_create fails.
 ****************************************************************************/

static int attach_fullscreen_image(lv_obj_t *parent,
                                   const lv_img_dsc_t *src)
{
  lv_obj_t *img;

  if (src == NULL)
    {
      return 0; /* No asset selected - black screen */
    }

  img = lv_img_create(parent);
  if (img == NULL)
    {
      printf("screen_manager: lv_img_create failed\n");
      return -ENOMEM;
    }

  lv_img_set_src(img, src);
  lv_obj_set_pos(img, 0, 0);

  return 0;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: screen_manager_init
 *
 * Description:
 *   Phase 1: Create bare screen skeletons, load SCREEN_SPLASH.
 *   Must be called after fb_handler_init(), before threads
 *   start. No image assets or widgets are created here.
 *
 * Returned Value:
 *   0 on success, negative errno on failure.
 ****************************************************************************/

int screen_manager_init(void)
{
  int i;

  if (g_current != SCREEN_COUNT)
    {
      return -EBUSY;
    }

  for (i = 0; i < SCREEN_COUNT; i++)
    {
      g_screens[i] = build_screen_skeleton();
      if (g_screens[i] == NULL)
        {
          printf("screen_manager: "
                 "build skeleton %d failed\n", i);
          return -ENOMEM;
        }
    }

  lv_scr_load(g_screens[SCREEN_SPLASH]);
  g_current = SCREEN_SPLASH;

  printf("screen_manager: phase 1 done, "
         "splash loaded (black)\n");
  return 0;
}

/****************************************************************************
 * Name: screen_manager_setup_assets
 *
 * Description:
 *   Phase 2: Attach image assets and build widget tree.
 *   MUST be called from lvgl_thread context ONLY.
 *   Called once at the start of lvgl_thread, before the
 *   render loop.
 *
 *   Asset selection is determined at compile time:
 *     SPLASH_ASSET - splash screen image (or NULL)
 *     THEME_ASSET  - dashboard + theme background (or NULL)
 *
 ****************************************************************************/

void screen_manager_setup_assets(void)
{
  int ret;

  if (g_assets_ready)
    {
      return;
    }

  /* --- Splash screen: background image from flash --- */

  ret = attach_fullscreen_image(g_screens[SCREEN_SPLASH],
                                SPLASH_ASSET);
  if (ret < 0)
    {
      printf("screen_manager: splash asset failed: %d\n",
             ret);
    }

  /* --- Dashboard: theme background + widgets --- */

  ret = attach_fullscreen_image(g_screens[SCREEN_DASHBOARD],
                                THEME_ASSET);
  if (ret < 0)
    {
      printf("screen_manager: "
             "dashboard theme failed: %d\n", ret);
    }

  /* Build widget tree on dashboard screen.
   * widgets_init() creates objects on the active screen,
   * so we must temporarily load the dashboard.
   */

  lv_scr_load(g_screens[SCREEN_DASHBOARD]);

  ret = widgets_init();
  if (ret < 0)
    {
      printf("screen_manager: widgets_init failed: %d\n",
             ret);
    }

  /* --- Theme: same background, no widgets --- */

  ret = attach_fullscreen_image(g_screens[SCREEN_THEME],
                                THEME_ASSET);
  if (ret < 0)
    {
      printf("screen_manager: theme asset failed: %d\n",
             ret);
    }

  /* Restore splash as active screen */

  lv_scr_load(g_screens[SCREEN_SPLASH]);

  g_assets_ready = true;

  printf("screen_manager: phase 2 done, assets ready\n");
}

/****************************************************************************
 * Name: screen_manager_load
 *
 * Description:
 *   Switch to the requested screen.
 *   No-op if the requested screen is already active.
 *   Safe to call from main thread or button handler.
 *
 * Input Parameters:
 *   screen - Target screen identifier
 ****************************************************************************/

void screen_manager_load(screen_id_t screen)
{
  if (screen >= SCREEN_COUNT)
    {
      printf("screen_manager: invalid screen id %d\n",
             screen);
      return;
    }

  if (screen == g_current)
    {
      return;
    }

  lv_scr_load(g_screens[screen]);

  g_current = screen;

  printf("screen_manager: loaded screen %d\n",
         (int)screen);
}

/****************************************************************************
 * Name: screen_manager_current
 *
 * Description:
 *   Return the currently active screen identifier.
 *
 * Returned Value:
 *   Current screen_id_t value.
 ****************************************************************************/

screen_id_t screen_manager_current(void)
{
  return g_current;
}
