/****************************************************************************
 * apps/hmi_manager/uiux/screen/screen_manager.c
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to you under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 * implied. See the License for the specific language governing
 * permissions and limitations under the License.
 *
 ****************************************************************************/

/****************************************************************************
 * Design: Two-phase initialization
 *
 * Phase 1 - screen_manager_init() - called from main() before threads:
 *   Creates bare lv_obj_t screens (no image objects, no widgets).
 *   Loads SCREEN_SPLASH as active screen (black until phase 2).
 *   Safe because lv_obj_create(NULL) does not trigger rendering.
 *
 * Phase 2 - screen_manager_setup_assets() - called from lvgl_thread:
 *   Attaches lv_img to splash screen (lv_img_create is LVGL-thread-safe).
 *   Calls widgets_init() on dashboard screen in correct LVGL context.
 *   This is the ONLY correct place to create LVGL objects with assets.
 *
 ****************************************************************************/

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include <stdio.h>
#include <errno.h>
#include <lvgl/lvgl.h>

#include "screen_manager.h"
#include "../widgets.h"

/* Splash screen asset - generated by png2code.py.
 * Symbol declared here so only screen_manager.c depends on it.
 */

/* extern const lv_img_dsc_t img_bifrostox2; */

extern const lv_img_dsc_t img_main_retro;

/****************************************************************************
 * Private Data
 ****************************************************************************/

/* One lv_obj_t* per screen - created once in phase 1, kept alive.
 * LVGL screens are lightweight; only the active one is rendered.
 */

static lv_obj_t *g_screens[SCREEN_COUNT];
static screen_id_t g_current = SCREEN_COUNT; /* invalid sentinel */
static bool g_assets_ready   = false;

/****************************************************************************
 * Private Functions
 ****************************************************************************/

/****************************************************************************
 * Name: build_screen_skeleton
 *
 * Description:
 *   Create a bare black screen with no child objects.
 *   Safe to call before lvgl_thread starts.
 *
 * Returned Value:
 *   Pointer to lv_obj_t, or NULL on failure.
 ****************************************************************************/

static lv_obj_t *build_screen_skeleton(void)
{
  lv_obj_t *scr;

  scr = lv_obj_create(NULL);
  if (scr == NULL)
    {
      return NULL;
    }

  lv_obj_set_style_bg_color(scr, lv_color_hex(0x000000), 0);
  lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, 0);

  return scr;
}

/****************************************************************************
 * Public Functions
 ****************************************************************************/

/****************************************************************************
 * Name: screen_manager_init
 *
 * Description:
 *   Phase 1: Create bare screen skeletons, load SCREEN_SPLASH.
 *   Must be called after fb_handler_init(), before threads start.
 *   No image assets or widgets are created here.
 *
 * Returned Value:
 *   0 on success, negative errno on failure.
 ****************************************************************************/

int screen_manager_init(void)
{
  int i;

  if (g_current != SCREEN_COUNT)
    {
      return -EBUSY;
    }

  for (i = 0; i < SCREEN_COUNT; i++)
    {
      g_screens[i] = build_screen_skeleton();
      if (g_screens[i] == NULL)
        {
          printf("screen_manager: build skeleton %d failed\n", i);
          return -ENOMEM;
        }
    }

  lv_scr_load(g_screens[SCREEN_SPLASH]);
  g_current = SCREEN_SPLASH;

  printf("screen_manager: phase 1 done, splash loaded (black)\n");
  return 0;
}

/****************************************************************************
 * Name: screen_manager_setup_assets
 *
 * Description:
 *   Phase 2: Attach image assets and build widget tree.
 *   MUST be called from lvgl_thread context ONLY.
 *   Called once at the start of lvgl_thread, before the render loop.
 *
 ****************************************************************************/

void screen_manager_setup_assets(void)
{
  lv_obj_t *img;
  lv_obj_t *prev;
  int ret;

  if (g_assets_ready)
    {
      return;
    }

  /* --- Splash: attach background image from flash --- */

  img = lv_img_create(g_screens[SCREEN_SPLASH]);
  if (img != NULL)
    {
      /* lv_img_set_src(img, &img_bifrostox2); */
      
      lv_img_set_src(img, &img_main_retro);
      
      lv_obj_set_pos(img, 0, 0);
    }
  else
    {
      printf("screen_manager: lv_img_create failed\n");
    }

  /* --- Dashboard: build widget tree in correct LVGL context --- */

  prev = lv_screen_active();
  lv_scr_load(g_screens[SCREEN_DASHBOARD]);

  ret = widgets_init();
  if (ret < 0)
    {
      printf("screen_manager: widgets_init failed: %d\n", ret);
    }

  /* Restore splash as active screen */

  lv_scr_load(g_screens[SCREEN_SPLASH]);

  g_assets_ready = true;

  printf("screen_manager: phase 2 done, assets ready\n");
}

/****************************************************************************
 * Name: screen_manager_load
 *
 * Description:
 *   Switch to the requested screen with a fade animation.
 *   No-op if the requested screen is already active.
 *   Safe to call from main thread or button handler.
 *
 * Input Parameters:
 *   screen - Target screen identifier
 ****************************************************************************/

void screen_manager_load(screen_id_t screen)
{
  if (screen >= SCREEN_COUNT)
    {
      printf("screen_manager: invalid screen id %d\n", screen);
      return;
    }

  if (screen == g_current)
    {
      return;
    }

  /* transition in fade-in
  lv_scr_load_anim(g_screens[screen],
                   LV_SCR_LOAD_ANIM_FADE_IN,
                   SCREEN_ANIM_MS,
                   0,
                   false);
  */
  
  lv_scr_load(g_screens[screen]); /* no transition */

  g_current = screen;

  printf("screen_manager: loaded screen %d\n", (int)screen);
}

/****************************************************************************
 * Name: screen_manager_current
 *
 * Description:
 *   Return the currently active screen identifier.
 *
 * Returned Value:
 *   Current screen_id_t value.
 ****************************************************************************/

screen_id_t screen_manager_current(void)
{
  return g_current;
}
