#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.

"""
png2code.py - Convert PNG to LVGL RGB565 C array for STM32 flash.

Target : STM32H753ZI, ST7796 480x320, LVGL 8.x/9.x
Output : apps/hmi_manager/uiux/assets/<symbol>.c + <symbol>.h

Usage:
    python3 png2code.py <input.png> <symbol> [--resize WxH]
    python3 png2code.py <input.png> <symbol> [--outdir PATH]

Examples:
    python3 png2code.py png/splash.png img_splash
    python3 png2code.py png/splash.png img_splash --resize 480x320
    python3 png2code.py png/dash.png img_dashboard \\
        --resize 480x320 \\
        --outdir ../apps/hmi_manager/uiux/assets

Dependencies:
    pip install Pillow
"""

import sys
import os
import argparse
from datetime import datetime

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow not installed. Run: pip install Pillow")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

DISPLAY_W      = 480
DISPLAY_H      = 320
WARN_KB        = 400        # warn if single asset exceeds this (KB)
BYTES_PER_LINE = 12         # byte columns in generated C array

# ---------------------------------------------------------------------------
# RGB conversion
# ---------------------------------------------------------------------------

def rgb888_to_rgb565(r: int, g: int, b: int) -> int:
    """
    Pack 8-bit R, G, B channels into 16-bit RGB565.

    Bit layout (MSB to LSB):
      [15:11] R - 5 bits
      [10:5]  G - 6 bits
      [4:0]   B - 5 bits
    """
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

# ---------------------------------------------------------------------------
# Image loading and conversion
# ---------------------------------------------------------------------------

def load_and_convert(path: str, resize) -> tuple:
    """
    Load a PNG file, optionally resize, and convert to RGB565.

    Parameters
    ----------
    path   : path to input PNG file
    resize : (width, height) tuple or None

    Returns
    -------
    (width, height, pixels) where pixels is a list of uint16_t values
    in row-major order (left-to-right, top-to-bottom).
    """
    img = Image.open(path)

    # Drop alpha channel if present (RGBA, LA, PA -> RGB)

    if img.mode != 'RGB':
        img = img.convert('RGB')

    if resize is not None:
        img = img.resize(resize, Image.LANCZOS)

    w, h   = img.size
    pixels = []

    for y in range(h):
        for x in range(w):
            r, g, b = img.getpixel((x, y))
            pixels.append(rgb888_to_rgb565(r, g, b))

    return w, h, pixels

# ---------------------------------------------------------------------------
# C source generation
# ---------------------------------------------------------------------------

def gen_c(symbol: str, w: int, h: int,
          pixels: list, src_name: str) -> str:
    """
    Generate .c file content.

    The pixel array is declared as static const uint8_t[], which the
    linker places in .rodata (flash). LVGL reads directly via pointer
    - no RAM copy is ever made.

    Pixels are stored as little-endian uint16_t split into two bytes:
      pixel 0xRRGG -> byte[0] = low byte, byte[1] = high byte
    """
    ts       = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    total    = w * h * 2
    total_kb = total / 1024

    # Flatten uint16_t pixels to uint8_t byte list (little-endian)

    raw = []
    for px in pixels:
        raw.append(px & 0xFF)
        raw.append((px >> 8) & 0xFF)

    # Format byte array body

    rows = []
    for i in range(0, len(raw), BYTES_PER_LINE):
        chunk = raw[i:i + BYTES_PER_LINE]
        comma = "," if (i + BYTES_PER_LINE) < len(raw) else ""
        rows.append(
            "    " + ", ".join(f"0x{b:02X}" for b in chunk) + comma
        )

    array_body = "\n".join(rows)

    return "\n".join([
        "/**" + "*" * 71,
        f" * apps/hmi_manager/uiux/assets/{symbol}.c",
        " *",
        f" * Auto-generated by png2code.py on {ts}",
        f" * Source     : {src_name}",
        f" * Resolution : {w}x{h} px",
        " * Format     : RGB565, little-endian uint16_t",
        f" * Flash usage: {total} bytes ({total_kb:.1f} KB)",
        " *",
        " * DO NOT EDIT MANUALLY.",
        f" * Regenerate : python3 png2code.py {src_name} {symbol}",
        " *" + "*" * 71 + "/",
        "",
        "#include <lvgl/lvgl.h>",
        f"#include \"{symbol}.h\"",
        "",
        "/* Pixel data - .rodata section (flash), never copied to RAM */",
        "",
        f"static const uint8_t {symbol}_map[] =",
        "{",
        array_body,
        "};",
        "",
        f"/* LVGL descriptor - pass &{symbol} to lv_img_set_src() */",
        "",
        f"const lv_img_dsc_t {symbol} =",
        "{",
        "    .header =",
        "    {",
        "        .cf          = LV_IMG_CF_TRUE_COLOR,",
        "        .always_zero = 0,",
        "        .reserved    = 0,",
        f"        .w           = {w}U,",
        f"        .h           = {h}U,",
        "    },",
        f"    .data_size = {total}U,",
        f"    .data      = {symbol}_map,",
        "};",
        "",
    ])


def gen_h(symbol: str, w: int, h: int) -> str:
    """Generate .h file with extern declaration."""
    guard = f"{symbol.upper()}_H"
    return "\n".join([
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#include <lvgl/lvgl.h>",
        "",
        f"/* {w}x{h} RGB565 image asset - stored in flash */",
        "",
        f"extern const lv_img_dsc_t {symbol};",
        "",
        f"#endif /* {guard} */",
        "",
    ])

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_resize(s: str):
    """Parse 'WxH' string into (int, int) tuple."""
    try:
        w, h = s.lower().split('x')
        return (int(w), int(h))
    except Exception:
        raise argparse.ArgumentTypeError(
            f"Invalid size '{s}'. Expected format: 480x320"
        )


def main():
    parser = argparse.ArgumentParser(
        description=(
            "Convert PNG to LVGL RGB565 C array for STM32 flash. "
            "Outputs <symbol>.c and <symbol>.h."
        )
    )
    parser.add_argument(
        "input",
        help="Input PNG file path"
    )
    parser.add_argument(
        "symbol",
        help="C symbol name (e.g. img_splash, img_dashboard)"
    )
    parser.add_argument(
        "--resize", type=parse_resize, metavar="WxH",
        help=(
            f"Resize image before conversion. "
            f"Display is {DISPLAY_W}x{DISPLAY_H}. "
            f"Example: --resize 480x320"
        )
    )
    parser.add_argument(
        "--outdir", default=".",
        help="Output directory for generated files (default: .)"
    )
    args = parser.parse_args()

    if not os.path.isfile(args.input):
        print(f"ERROR: File not found: {args.input}")
        sys.exit(1)

    print(f"Input  : {args.input}")
    print(f"Symbol : {args.symbol}")

    w, h, pixels = load_and_convert(args.input, args.resize)
    total_kb     = (w * h * 2) / 1024

    print(f"Size   : {w}x{h} px")
    print(f"Flash  : {total_kb:.1f} KB")

    if w > DISPLAY_W or h > DISPLAY_H:
        print(
            f"WARNING: Image {w}x{h} exceeds display "
            f"{DISPLAY_W}x{DISPLAY_H}. "
            f"Use --resize {DISPLAY_W}x{DISPLAY_H}."
        )

    if total_kb > WARN_KB:
        print(
            f"WARNING: Asset is {total_kb:.1f} KB. "
            f"Verify remaining flash budget."
        )

    os.makedirs(args.outdir, exist_ok=True)

    c_path = os.path.join(args.outdir, f"{args.symbol}.c")
    h_path = os.path.join(args.outdir, f"{args.symbol}.h")

    with open(c_path, 'w') as f:
        f.write(gen_c(args.symbol, w, h, pixels,
                      os.path.basename(args.input)))

    with open(h_path, 'w') as f:
        f.write(gen_h(args.symbol, w, h))

    print(f"Output : {c_path}")
    print(f"Output : {h_path}")
    print("Done.")


if __name__ == "__main__":
    main()
